# Generated by Django 3.0.2 on 2020-01-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='kpi',
            constraint=models.UniqueConstraint(fields=('name',), name='unique'),
        ),
    ]
